name: github_action_01

on:
   push:
     branches:
       - master


jobs:
   test:
      runs_on: ubuntu-latest

      steps:
        - name: check out code
          uses: actions/checkout@v2 
        
        - name: set up python
          run: 
             python -m pip install --upgrade pip
             pip install -r requirments.txt
        
        - name: run test
          run: pytest 
             





